services:
  - type: web
    name: crmbackend
    env: python
    plan: free
    buildCommand: "pip install -r requirement.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn crmbackend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "crmbackend-xgc8.onrender.com,localhost"
      - key: DATABASE_URL
        fromDatabase:
          name: crmbackend-db
          property: connectionString
